package_assets: on

javascripts:
    all:
        - public/javascripts/vendor/jquery.min.js
        - public/javascripts/vendor/mustache.js
        - public/javascripts/vendor/bootstrap-dropdown.js
        - public/javascripts/k-core.js
        - public/javascripts/k-util.js
        - public/javascripts/k-data.js
        - public/javascripts/k-manager.js
        - public/javascripts/k-component.js
        - public/javascripts/k-message.js
        - public/javascripts/k-validation.js
        - public/javascripts/k-form.js
    
    newkit:
        - public/javascripts/components/k-newkit.js
    
    kit:
        - public/javascripts/components/k-kit-title.js
        - public/javascripts/components/k-kit-newitem.js
        - public/javascripts/components/k-kit-edititem.js
        - public/javascripts/components/k-kit.js

    howitworks:
        - public/javascripts/components/k-howitworks.js

stylesheets:
    all:
        - public/stylesheets/vendor/bootstrap.min.css
        - public/stylesheets/k-core.css
        - public/stylesheets/k-layout.css
        - public/stylesheets/k-typography.css
        
    home:
        - public/stylesheets/k-home.css
        
    kit:
        - public/stylesheets/k-kit.css
    
    howitworks:
        - public/stylesheets/k-howitworks.css